{{- if .Values.components.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.components.storage.name }}
  namespace: {{ include "clara-train.namespace" . }}
  labels:
    {{- include "clara-train.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.components.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.components.storage.size }}
  storageClassName: {{ .Values.components.storage.storageClassName }}
{{- end }}
